### ISSUE TITLE
EPA Breakdown Issues

### ISSUE THREAD

**Issue by Sprink02** [avgupta456/statbotics#277]
EPA Breakdown has a few issues:
Certain points will be under 0. I do understand that this team probably has cost the team points but cycles and links are affected by this and can be negative.

**Comment by avgupta456** [comment]
It might seem counterintuitive at first, but cycle and link EPAs can be negative. For example, if a team claims responsibility for a task in auto but fails to deliver, they might reduce the number of auto game pieces scored. If a team is scoring pieces low and takes up space near the grid, this might reduce the alliance's middle and top game pieces scored.

While most of the negative results are due to noise and random chance, I don't want to hide this and obscure some second order effects.
